# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='real_url',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
